[[override]]
  name = "github.com/docker/distribution"
  revision = "edc3ab29cdff8694dd6feb85cfeb4b5f1b38ed9c"

[[override]]
  name = "github.com/vmware/photon-controller-go-sdk"
  version = "PROMOTED-488"

[[constraint]]
  name = "github.com/hetznercloud/hcloud-go"
  version = "v1.3.0"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.9.2"

[[constraint]]
  name = "k8s.io/kubernetes"
  version = "1.9.2"
